### ISSUE TITLE
logging set-up code

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1679]
Do we need the following logging set-up code in src/ansys/fluent/core/__init__.py?

```
pyfluent_logging.root_config()

env_logging_level = os.getenv("PYFLUENT_LOGGING")
if env_logging_level:
    if isinstance(env_logging_level, str):
        if env_logging_level.isdigit():
            env_logging_level = int(env_logging_level)
        else:
            env_logging_level = env_logging_level.upper()
    if env_logging_level in [0, "OFF"] or pyfluent_logging.is_active():
        pass
    else:
        print("PYFLUENT_LOGGING environment variable found, enabling logging...")
        pyfluent_logging.enable(env_logging_level)

```

Or is the yaml configuration sufficient. Please give your feedback.

**Comment by raph-luc** [comment]
The most important part in `__init__.py` is the `pyfluent_logging.root_config()` call, which sets up the root/ancestor logger, and enables formatting and redirection to console for the warning level (and above) messages for logging.

If we want to automatically enable logging using the `PYFLUENT_LOGGING` environment variable, in my understanding we also want to do it as early as possible in the start up process, before other PyFluent modules are loaded and start making use out of the child loggers.

The YAML logging config file is only read on `pyfluent_logging.enable()`, and the YAML file is also only for the child loggers that output to the `.log` file (loading is also when the `.log` file is created). 

@seanpearsonuk Is the concern doing too many things on `__init__.py`? I think this would be one of the exceptions that we probably should set up on `__init__.py` as we want logging used throughout PyFluent (not only logging to file, which is optional, but also for warning/error messages to console, which is not optional currently).

**Comment by raph-luc** [comment]
See the PR above for an alternate way to initialize logging, cleaning up the `__init__.py` module a bit. 

There are many different ways we could go about setting up logging, @mkundu1 @seanpearsonuk please let me know what your thoughts are.

**Comment by seanpearsonuk** [comment]
I'm not completely clear about everything yet, but I have a few points/questions:
- is it necessary to depend on the environment variable or should everything just be configured in the yaml file?
- yes, I think it would be good to extract the chunk of logging code out of `__init__.py` into `logging.py`
- where we load the yaml file and call `dictConfig`, is all that equivalent to calling `fileConfig`?

**Comment by raph-luc** [comment]
> * is it necessary to depend on the environment variable or should everything just be configured in the yaml file?

Currently, PyFluent does not depend on the `PYFLUENT_LOGGING` environment variable; the environment variable is only used to automatically enable logging to file on start-up without having to manually `pyfluent.logging.enable()`. 

I believe (and my intention) is that the env var is more helpful for development rather than typical PyFluent usage. End users would just add  `pyfluent.logging.enable()` to their scripts if they want debug logging to file (which in my understanding should be the exception rather than the usual). 

> * where we load the yaml file and call `dictConfig`, is all that equivalent to calling `fileConfig`?

Yes, `dictConfig` is sort of a newer and improved version of `fileConfig`, with extended functionality. Documentation talks about this here: https://docs.python.org/3/library/logging.config.html#logging-config-fileformat.
