### ISSUE TITLE
grpc error during initial connection

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#1747]
Currently, any grpc error during initial connection results in a timeout with the runtime error "The connection to the Fluent server could not be established...".  It is better to fail early in those situations by exposing the internal grpc error which may provide useful triaging information from the user's system. 

Relevant is the test test_create_session_from_server_info_file_with_wrong_password which is checking the failure due to the timeout (with the 100 s wait) instead of an immediate failure due to password mismatch.

@raph-luc (originally found the issue)

**Comment by raph-luc** [comment]
Related example test failures:
https://github.com/ansys/pyfluent/actions/runs/5457287691/jobs/9931174803?pr=1759
https://github.com/ansys/pyfluent/actions/runs/5357964161/jobs/9719803655?pr=1715
https://github.com/ansys/pyfluent/actions/runs/5355190417/jobs/9713258474?pr=1712

**Comment by raph-luc** [comment]
The catched gRPC exceptions when these random failures occur are:

First this exception once: 
`HealthCheckService.status() caught RuntimeError: End of TCP stream`

and then repeatedly every second on every gRPC attempt until timeout: 
`HealthCheckService.status() caught RuntimeError: failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:63599: connection attempt timed out before receiving SETTINGS frame`

Any ideas what may be causing these seemingly random failures? The Fluent client remains open after this, but haven't checked if it is responsive or not as running it without GUI.

This happens not only when launching Fluent, but also when connecting to an already existing Fluent server (e.g. also happens in the middle of a `tests/test_streaming_services.py::test_transcript` run)

There is no particular test where this seems to happen more often than others, and nothing is written to the `.trn` file when this happens

Also, we probably should consider raising different exceptions for these different gRPC errors rather than `RuntimeError` for all/most of them, maybe we could parse the RpcError text and raise an appropriate exception if we can identify it based on the text?

**Comment by raph-luc** [comment]
First one to be logged on GitHub: https://github.com/ansys/pyfluent/actions/runs/5695317917/job/15438219836

Same issue as I had one time locally, as described in my previous message:
`INFO     pyfluent.general:health_check.py:88 HealthCheckService.status() caught RuntimeError: failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:34431: connection attempt timed out before receiving SETTINGS frame`

Until timeout
