### ISSUE TITLE
Make the mapped path within container easily visible to users (either through logging or through a property at session level).

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2865]

**Comment by raph-luc** [comment]
I think this could be through convenience functions as well, to more easily fetch what the PyFluent workdir is in the host system, and what the Fluent workdir is in the guest container system.

Some of the confusion here is probably unavoidable IMO due to the host-guest architecture, with PyFluent and Fluent in different systems, unless we wrap all TUI calls and file operations to transform the paths for the users so they don't have to think about this.
