### ISSUE TITLE
meshing utilities return types and docstrings

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#3125]
From the internal chat:

"I have been using meshing queries recently for scripts and it worked well, when trying again today I realize that the queries are now utilities. 
 
While the reduction of functions is a good thing, I have trouble to do what I could before. 
For instance the get_face_zones function works fine with filter argument giving me a list of zones, but for xyz_coordinates and maximum entity_count I am surprised by the output. For xyz_coordinates I would expect to get a list even if only one value is returned ; otherwise the same command can output multiple types. For maximum_entity_count I could not get any zone, I am wondering if I understand correctly that one (I expected to get zones with less facets than the given number as in Selection Helper). It also does not seem to return a list even though I would expect one. Shouldn't it be an integer and not a float ? 
 
I looked at the help but it does not give much info on the arguments and outputs."
  
 Please could you look into it? It seems that some of the the return types might be varying for a given query, and this is presumably not by design.  It also seems that the return type is missing from the help results. I will create a GitHub issue.

**Comment by ddamadori** [comment]
I have a comment/question here though. I understand that the baseline idea is to make python APIs as close as possible to the TUI ones. But here we clearly see a situation where this results in a not very pythonic solution, as a function that can return either a list of integers or a single integer depending on the inputs can lead to crashes when put within a script that relies on the funciton output. Something like:
### scenario 1
```
for zone in meshing_utilities.get_face_zones(maximum_entity_count=500, only_boundary=True):
     print(zone)
```
Will work, whereas:
### scenario 2
```
for zone in meshing_utilities.get_face_zones(maximum_entity_count=500, xyz_coordinates=[1,2,3]):
      print(zone)
```
Will crash.
 
Also, in the specific case that initiated the discussion, if the intention is to sum the two outputs of the two calls to get_face_zones, it is not possible to just do a summation as one would be a list and one an integer. 
 
This means that one would have to write several lines of code with if statements to assess the type of the output and consequently either append or extend lists...

Additionally, it seems that the documentation is not super consistent and lacks of examples. At the moment it does not entirely follow the python documentation convention. Often the method is just shown as member of a class, instead of being followed by the arguments, which makes it difficult to even understand whether it takes arguments or key arguments:
![image](https://github.com/user-attachments/assets/fb34157a-4a89-450d-8556-37227eb481c3)

**Comment by seanpearsonuk** [comment]
@ddamadori Thanks for your feedback. The variation in return type is a bug and is being addressed. We are also improving the documentation and help information.
