### ISSUE TITLE
Cleanup pyfluent.EXAMPLES_PATH before running unittest job

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#791]

**Comment by mkundu1** [comment]
Should be done as a part of pytest setup step.

**Comment by lagacep-ans** [comment]
@mkundu1 there is a general issue with pytest and version number
 - Need to be able to specify the fluent version when running locally (not using PYFLUENT_LAUNCH_CONTAINER )
 - The test test_manual_fluent_version_setting is breaking the globally stored default version number "22.2" it will leave it in "23.1" state
    ... the version number should be backed up
    
    Note that in my [PR](https://github.com/pyansys/pyfluent/pull/754), i do add an optional command line argument for codegen/allapigen , we should have a consistent method to run codegen/pytest/... with a specified version number.   I can revise the PR if we choose a different mechanism.


(Then, once this issue is settled, we'll need to discuss how to handle icing regressions, i would like to have a simple one, but it requires an enterprise license.  This might be some additional argument/environment variable in the test environment)

**Comment by lagacep-ans** [comment]
Can see the impact of running, or not test_launcher in a local pytest sequence.  Running plain "pytest" is also not failing test_general.

![image](https://user-images.githubusercontent.com/95301632/187297941-541c6048-6b19-4184-8445-b03b126e3351.png)

Unsure if this affects automated unit tests on github

**Comment by seanpearsonuk** [comment]
@prmukherj re these merges, do they close this issue? cc: @mkundu1

**Comment by seanpearsonuk** [comment]
@mkundu1 Can we close this?

**Comment by mkundu1** [comment]
We are already doing this during github run which is sufficient.
