### ISSUE TITLE
Problem: Saving the file in different location

### ISSUE THREAD

**Issue by pavankumarkonchada** [ansys/pyfluent#898]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

How to save the files which ran successfully in required location

### 📝 Steps to reproduce

I have followed the same procedure mentioned in examples and it is getting saved in the below location
C:\Users\cadfem\AppData\Local\ansys_fluent_core\ansys_fluent_core

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
All the required packages
```

**Comment by tanieee28** [comment]
Hi, I have a similar question of how to modify the file path of meshing results files from default (..\AppData\Local\ansys_fluent_core\ansys_fluent_core\examples\).
Could not find any option in the official documentation [here](https://fluent.docs.pyansys.com/user_guide/). 
Need help here.

**Comment by seanpearsonuk** [comment]
Perhaps we can update the documentation to make it clearer what is going on and what the user needs to do to specify the location of the file they want to use.

**Comment by raph-luc** [comment]
The 'specifying where to save files' part of this issue has been resolved through https://github.com/pyansys/pyfluent/pull/1582, when running one of the examples with `download_file`, specify the file save location with `download_file(..., save_path=...)`, as Fluent by default saves output files to the same folder where it read input files from.

The documentation part of this issue is still open, need to update documentation and examples to reflect this.

**Comment by seanpearsonuk** [comment]
Assigning to @hpohekar for the doc part
